
-- USER is a reserved keyword with Postgres
-- You must use double quotes in every query that user is in:
-- ex. SELECT * FROM "user";
-- Otherwise you will have errors!
CREATE TABLE "user" (
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR (80) UNIQUE NOT NULL,
    "password" VARCHAR (1000) NOT NULL
);


-- List of Minnesota Counties

CREATE TABLE "counties" (
	"id" SERIAL PRIMARY KEY,
	"name" VARCHAR(255)
);

INSERT INTO "counties" ("name") VALUES ('Aitkin'),
('Anoka'),
('Becker'),
('Beltrami'),
('Benton'),
('Big Stone'),
('Blue Earth'),
('Brown'),
('Carlton'),
('Carver'),
('Cass'),
('Chippewa'),
('Chisago'),
('Clay'),
('Clearwater'),
('Cook'),
('Cottonwood'),
('Crow Wing'),
('Dakota'),
('Dodge'),
('Douglas'),
('Faribault'),
('Fillmore'),
('Freeborn'),
('Goodhue'),
('Grant'),
('Hennepin'),
('Houston'),
('Hubbard'),
('Isanti'),
('Itasca'),
('Jackson'),
('Kanabec'),
('Kaniyohi'),
('Kittson'),
('Koochiching'),
('Lac Qui Parle'),
('Lake'),
('Lake Of The Wood'),
('Le Sueur'),
('Lincoln'),
('Lyon'),
('Mahnomen'),
('Marshall'),
('Martin'),
('McLeod'),
('Meeker'),
('Mille Lacs'),
('Morrison'),
('Mower'),
('Murray'),
('Nicollet'),
('Nobles'),
('Norman'),
('Olmsted'),
('Otter Tail'),
('Pennington'),
('Pine'),
('Pipestone'),
('Polk'),
('Pope'),
('Ramsey'),
('Red Lake'),
('Redwood'),
('Renville'),
('Rice'),
('Rock'),
('Roseau'),
('St. Louis'),
('Scott'),
('Sherburne'),
('Sibley'),
('Stearns'),
('Steele'),
('Stevens'),
('Swift'),
('Todd'),
('Traverse'),
('Wabasha'),
('Wadena'),
('Waseca'),
('Washington'),
('Watonwan'),
('Wilkin'),
('Winona'),
('Wright'),
('Yellow Medicine');

-- List of organizations

CREATE TABLE "organizations" (
	"id" serial PRIMARY KEY,
	"name" varchar(255),
	"logo" varchar(255),
	"type" varchar(255),
	"address_number" varchar(255),
	"address_street" varchar(255),
	"address_unit" varchar(255),
	"city" varchar(255),
	"state" varchar(255),
	"county" varchar(255),
	"zip" varchar(255),
	"notes" varchar(255)
);

INSERT INTO "organizations" ("name", "logo", "type", "address_number", "address_street", "address_unit", "city", "state", "county", "zip", "notes")

VALUES( '360 Communities','https://360communities.org/wp-content/uploads/2019/04/Menu-Logo-800.png','non-profit','501','State Hwy 13', '#112', 'Burnsville','MN','Dakota','55337', NULL),
('800 Workforce Center', 'http://www.800westbroadway.org/sites/default/files/logo_0_0.jpg','non-profit','800','West Broadway', NULL, 'Minneapolis','MN','Hennepin','55411', NULL),
('Minnesota Childrens Museum', 'http://mcm.org/wp-content/uploads/2015/08/mcm-logo.png','municipal','10', '7th St. W', NULL, 'St. Paul','MN','Ramsey','55102', NULL),
('Gethsemane Lutheran Church', 'https://www.geth.org/wp-content/uploads/2019/05/gethsemane-logo.png','religious','2410','Stillwater RD E', NULL, 'Maplewood', 'MN', 'Ramsey', '55119', NULL),
('City of Bloomington', 'https://www.bloomingtonmn.gov/sites/default/themes/cob_omega/logo.png', 'municipal', '1800', 'W Old Shakopee Rd', NULL, 'Bloomington', 'MN', 'Hennepin', '55431', NULL),
('City of Brooklyn Center', NULL, 'municipal', '6301', 'Shingle Creek PKWY', NULL, 'Brooklyn Center', 'MN', 'Hennepin', 'MN', '55430', NULL),
('City of Burnsville', 'https://www.burnsville.org/ImageRepository/Document?documentID=18162', 'municipal', '12550', 'Nicollet Avenue', NULL, 'Burnsville', 'MN', 'Dakota', '55337', NULL),
('City of South St. Paul', 'https://www.southstpaul.org/ImageRepository/Document?documentID=3949', 'municipal', '125', '3rd Ave N', NULL, 'South St. Paul', 'MN', 'Dakota', '55075', NULL),
('Hazel Park Rec Center', NULL, 'municipal', '945', 'Hazel St. N', NULL, 'St. Paul', 'MN', 'Ramsey', '55119', NULL),
('Closet of Hope', NULL, 'religious', '10150', 'Xerxes Ave S.', NULL, 'Bloomington', 'MN', 'Hennepin', '55431', NULL),
('Metro State University', NULL, 'municipal', '700', '7th ST', NULL, 'St. Paul', 'MN', 'Ramsey', '55106', NULL),
('Western Service Center', NULL, 'municiapl', '14955', 'Galaxie Avenue', NULL, 'Apple Valley', 'MN', 'Dakota', '55124', NULL),
('Dakota City Heritage Village', 'http://www.dakotacity.org/wp-content/uploads/2015/03/DCHV.Logo1_.jpg', 'municipal', '4008', '220th ST', NULL, 'Farmington', 'MN', 'Dakota', '55024', NULL),
('Easter Lutheran Church', 'https://easter.org/wordpress/wp-content/uploads/2017/08/Easter_Logo_v2f-Notag-NEWWEB3-300x161.jpg', 'religious', '4200', 'Pilot Knob RD', NULL, 'Eagan', 'MN', 'Dakota', '55122', NULL),
('Community Education Burnsville', 'https://www.communityed191.org/thumbnails/www.communityed191.org/files/images/logo_0_auto_auto.png', '200', 'W Burnsville PKWY', 'Suite 100', 'Burnsville', 'MN', 'Dakota', '55337', NULL)