CREATE TABLE "counties" (
	"county_id" SERIAL PRIMARY KEY,
	"county_name" VARCHAR(255)
);

INSERT INTO "counties" ("county_name") VALUES ('Aitkin'),
('Anoka'),
('Becker'),
('Beltrami'),
('Benton'),
('Big Stone'),
('Blue Earth'),
('Brown'),
('Carlton'),
('Carver'),
('Cass'),
('Chippewa'),
('Chisago'),
('Clay'),
('Clearwater'),
('Cook'),
('Cottonwood'),
('Crow Wing'),
('Dakota'),
('Dodge'),
('Douglas'),
('Faribault'),
('Fillmore'),
('Freeborn'),
('Goodhue'),
('Grant'),
('Hennepin'),
('Houston'),
('Hubbard'),
('Isanti'),
('Itasca'),
('Jackson'),
('Kanabec'),
('Kaniyohi'),
('Kittson'),
('Koochiching'),
('Lac Qui Parle'),
('Lake'),
('Lake Of The Wood'),
('Le Sueur'),
('Lincoln'),
('Lyon'),
('Mahnomen'),
('Marshall'),
('Martin'),
('McLeod'),
('Meeker'),
('Mille Lacs'),
('Morrison'),
('Mower'),
('Murray'),
('Nicollet'),
('Nobles'),
('Norman'),
('Olmsted'),
('Otter Tail'),
('Pennington'),
('Pine'),
('Pipestone'),
('Polk'),
('Pope'),
('Ramsey'),
('Red Lake'),
('Redwood'),
('Renville'),
('Rice'),
('Rock'),
('Roseau'),
('St. Louis'),
('Scott'),
('Sherburne'),
('Sibley'),
('Stearns'),
('Steele'),
('Stevens'),
('Swift'),
('Todd'),
('Traverse'),
('Wabasha'),
('Wadena'),
('Waseca'),
('Washington'),
('Watonwan'),
('Wilkin'),
('Winona'),
('Wright'),
('Yellow Medicine'),
('Other')
;

CREATE TABLE "organizations" (
	"id" serial PRIMARY KEY,
	"org_name" varchar(255),
	"logo" varchar(255),
	"url" varchar(255),
	"type" varchar(255),
	"address_number" varchar(255),
	"address_street" varchar(255),
	"address_unit" varchar(255),
	"city" varchar(255),
	"state" varchar(255),
	"county_id" integer REFERENCES counties,
	"zip" varchar(255),
	"notes" varchar(255)
);

INSERT INTO "organizations" ("org_name", "logo", "url", "type", "address_number", "address_street", "address_unit", "city", "state", "county_id", "zip", "notes")
VALUES
('360 Communities', 'https://360communities.org/wp-content/uploads/2019/04/Menu-Logo-800.png', 'https://360communities.org/', null, null, null, null, 'Burnsville', 'MN', null, '55337', 'provide books to food shelves for families'), 
('Children''s Museum', 'https://pbs.twimg.com/profile_images/880172510582497280/FjzZ32zz_400x400.jpg', 'https://mcm.org/', null, null, null, null, 'St. Paul', 'MN', null, '55102', null),
('City of Bloomington', 'https://www.bloomingtonmn.gov/sites/default/files/images/city_of_bloomington_logo_vert_cmyk.jpg', 'https://www.bloomingtonmn.gov/', 'Municipal', null, null, null, 'Bloomington', 'MN', null, '55431', null),
('City of South St. Paul', 'https://www.crwflags.com/fotw/images/u/us-mnssp.gif', 'https://www.southstpaul.org/', 'Municipal', null, null, null, 'South St. Paul', 'MN', null, '55075', null),
('City of St. Paul', 'https://lh3.googleusercontent.com/proxy/G_FMh0xWkHRVk0m19XVa-a7WwVefJp9ueuma5kLsb6M59AnXGlzcNNOknNreQZ1dyGdKKFaYPSsWxSt8jFvnkXPWWwdrDHMau6fDxn64Z5bFZ3mRmnIGo9Sv7pSu0z2F1WjLYgeefOe4kJj63uGwR_ZwSiRont2h_tSSXjrGJ2_3myuEehAwHSNAeQ', 'https://www.stpaul.gov/', 'Municipal', null, null, null, 'St. Paul', 'MN', null, '55119', null),
('Closet of Hope', null, 'http://www.bcov.org/closet-of-hope/', 'Church', null, null, null, 'Religious', 'MN', null, '55431', null),
('Gideon Pond Elementary', null, 'https://www.isd191.org/schools/gideon-pond-elementary', 'Public School', null, null, null, 'Burnsville', 'MN', null, '55337', null),
('Sioux Trail Elementary', null, 'https://www.isd191.org/schools/sioux-trail-elementary', 'Public School', null, null, null, 'Burnsville', 'MN', null, '55337', null),
('Neighborhood House', 'https://media.glassdoor.com/sqll/2108163/neighborhood-house-mn-squarelogo-1533238373274.png', 'http://neighb.org/', null, null, null, null, 'St. Paul', 'MN', null, '55107', null),
('Northpoint Clinic', 'https://northsidefresh.org/wp-content/uploads/2019/10/northside-fresh_0011_northpoint-health-wellness-center-1.png', 'https://www.northpointhealth.org/', 'Clinic', null, null, null, 'Minneapolis', 'MN', null, '55411', null),
('Urban Ventures', 'https://pbs.twimg.com/profile_images/932038490900099072/VDXezHNX_400x400.jpg', 'https://urbanventures.org/', 'Nonprofit', null, null, null, 'Minneapolis', 'MN', null, '55408', null)

CREATE TABLE "contacts" (
	"id" serial PRIMARY KEY NOT NULL,
	"contact_name" varchar(255) NOT NULL,
	"title" varchar(255),
	"organizations_id" integer REFERENCES organizations,
	"phone_number" varchar(255) NOT NULL,
	"phone_number_type" varchar(255),
	"email" varchar(255),
	"notes" varchar(255)
);
